# .github/workflows/main.yml

name: Node.js CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}  

    - name: Install dependencies
      run: npm install  

    - name: Run ESLint
      run: npm run lint  
      continue-on-error: false

    - name: Run tests
      run: npm test  
